version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: pg_companies
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - cmd/.env
    depends_on:
      - db
    environment:
      GIN_MODE: ${MODE}
volumes:
  postgres_data:
